version: "3"
includes:
  protobuf:
    taskfile: ./protobuf
    dir: ./protobuf
  # go:
  #   taskfile: ./go
  #   dir: ./go
  # python:
  #   taskfile: ./python
  #   dir: ./python
env:
  PWD:
    sh: pwd
  GI_TYPELIB_PATH: "{{ .PWD }}/deps/local/lib/girepository-1.0:/usr/lib/girepository-1.0"
  LD_LIBRARY_PATH: "{{ .PWD }}/deps/.libs/"
tasks:
  default:
    deps: [build-app-backend]
  run-app:
    deps: [build-app-backend, build-gtk-nodes]
    cmds:
      - poetry run python ./python/cmd/walletmgr-app/
  setup:
    deps: [mkdir-deps, go-mod-download, poetry-install]
  build-app-backend:
    deps: [fix-code]
    sources:
      - ./go.mod
      - ./go.sum
      - ./**.go
    generates:
      - ./dist/walletmgr-app-backend
      - ./dist/walletmgr-app-backend.exe
    cmds:
      - go build -o ./dist/walletmgr-app-backend ./go/cmd/walletmgr-app-backend
  build-gtk-nodes:
    dir: ./deps
    status:
      - test -d {{ .PWD }}/deps/gtknodes
    cmds:
      - git clone https://github.com/aluntzer/gtknodes.git -b v0.1
      - >
        cd gtknodes &&
        ./autogen.sh && 
        ./configure --prefix={{ .PWD }}/deps/local &&
        make &&
        sudo make install
  mkdir-deps:
    cmds:
      - mkdir -p deps/local
  fix-code:
    deps: [go-mod-download, poetry-install]
    cmds:
      - task: protobuf
  go-mod-download:
    cmds:
      - go mod download
  poetry-install:
    cmds:
      - poetry install
  clean:
    cmds:
      - sudo rm -rf dist
      - sudo rm -rf deps
