# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_internal_pb2 as service__internal__pb2


class InternalAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTransactions = channel.unary_stream(
                '/grpc.InternalAppService/ListTransactions',
                request_serializer=service__internal__pb2.ListTransactionsRequest.SerializeToString,
                response_deserializer=service__internal__pb2.ListTransactionsStreamResponse.FromString,
                )


class InternalAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTransactions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTransactions': grpc.unary_stream_rpc_method_handler(
                    servicer.ListTransactions,
                    request_deserializer=service__internal__pb2.ListTransactionsRequest.FromString,
                    response_serializer=service__internal__pb2.ListTransactionsStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.InternalAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InternalAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.InternalAppService/ListTransactions',
            service__internal__pb2.ListTransactionsRequest.SerializeToString,
            service__internal__pb2.ListTransactionsStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
