version: "3"
tasks:
  default:
    vars:
      PWD:
        sh: pwd
    cmds:
      - protoc -I protobuf --proto_path=protobuf --python_out=. protobuf/*.proto
      - protoc -I protobuf --proto_path=protobuf --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protobuf/*.proto

  internal_service:
    internal: true